---
- name: Add repo {{ docker_repo_url }} to yum repositories
  yum_repository:
    name: docker-ce
    baseurl: "{{ docker_repo_url }}"
    gpgcheck: no
    description: Docker-CE

- name: Install Docker-CE
  yum:
    name: docker-ce
    state: present

- name: Ensure that Docker service enabled and running
  service:
    name: docker
    state: started
    enabled: yes
